### ISSUE TITLE
Nested Double and Single quotes throws error

### ISSUE THREAD

**Issue by jfeltkamp** [rackberg/para#11] opened 2017-04-18 15:41 UTC
A shell command line like this:
   git commit -m "RWRD8-537: created new tag for change 'region: content' included."

... throws this message: 
dara:   error: pathspec 'content included.' did not match any file(s) known to git.
alra:   error: pathspec 'content included.' did not match any file(s) known to git.
bobi:   error: pathspec 'content included.' did not match any file(s) known to git.
bora:   error: pathspec 'content included.' did not match any file(s) known to git.
rare:   error: pathspec 'content included.' did not match any file(s) known to git.

**Comment by rackberg** [comment] 2017-10-15 17:07
I'll close this ticket, because I am unable to reproduce the bug.

**Closed by rackberg** 2017-10-15 17:07 UTC
Labels: bug
